EMOJI_LIST = [":bowtie:", 
	":blush:", 
	":smirk:", 
	":kissing_closed_eyes:", 
	":satisfied:", 
	":stuck_out_tongue_winking_eye:", 
	":kissing:", 
	":sleeping:", 
	":anguished:", 
	":confused:", 
	":unamused:", 
	":disappointed_relieved:", 
	":disappointed:"
	":cold_sweat:"
	":sob:",
	":scream:", 
	":angry:", 
	":sleepy:", 
	":sunglasses:",
	":smiling_imp:", 
	":innocent:", 
	":smile:", 
	":smiley:", 
	":heart_eyes:", 
	":flushed:", 
	":grin:", 
	":stuck_out_tongue_closed_eyes:", 
	":kissing_smiling_eyes:", 
	":worried:", 
	":open_mouth:", 
	":hushed:", 
	":sweat_smile:", 
	":weary:", 
	":confounded:", 
	":persevere:", 
	":joy:", 
	":rage:", 
	":yum:", 
	":dizzy_face:", 
	":neutral_face:", 
	":laughing:", 
	":relaxed:", 
	":kissing_heart:", 
	":relieved:", 
	":wink:", 
	":grinning:", 
	":stuck_out_tongue:", 
	":frowning:", 
	":grimacing:", 
	":expressionless:", 
	":sweat:", 
	":pensive:", 
	":fearful:", 
	":cry:", 
	":astonished:", 
	":tired_face:", 
	":triumph:", 
	":mask:", 
	":imp:", 
	":no_mouth:", 
	# ":blush:", 
	# ":blush:", 
	# ":blush:", 
	# ":blush:", 
	# ":blush:", 
	# ":blush:", 
	# ":blush:", 
	# ":blush:", 
	# ":blush:", 
	# ":blush:", 
	# ":blush:", 
	# ":blush:", 
	# ":blush:", 
	# ":blush:", 
	# ":blush:", 
	# ":blush:", 
	# ":blush:", 
	# ":blush:", 
	# ":blush:", 
	# ":blush:", 
]